---
 - hosts: mhastudio
   remote_user: root
   become_user: root
   vars_files:
    - ../../../config.yaml
    - ./vars/var_mha.yaml
   tasks:
    - name: install dependents
      import_tasks: common/install_dependents.yaml

    - name: install mha node
      import_tasks: common/install_node.yaml

    - name: create mha user
      when: master_ip in ansible_all_ipv4_addresses
      import_tasks: common/create_mha_user.yaml

    - name: bind vip
      when: master_ip in ansible_all_ipv4_addresses
      import_tasks: common/bind_vip.yaml

    - name: install mha manager
      when: manager_ip in ansible_all_ipv4_addresses
      import_tasks: common/install_manager.yaml

    - name: config manager and start it
      when: manager_ip in ansible_all_ipv4_addresses
      import_tasks: common/config_manager.yaml
