---
 - name: unarchive php-5.6.31.tar.gz to remonte host 
   unarchive:
    src: "{{ mtls_base_dir + mtls_packages + 'php/'+ mtls_php}}"
    dest: /tmp/

 - name: copy install_php.sh to remonte host
   copy:
    src: ./template/install_php
    dest: /tmp/install_php.sh
    
 - name: install php
   shell: /bin/bash /tmp/install_php.sh

 - name: copy php.ini to remote
   copy: 
    src: ./template/php.ini
    dest: /usr/local/php/etc/php.ini

 - name: remove /usr/local/httpd/htdocs/index.html
   file:
    dest: /usr/local/httpd/htdocs/index.html
    state: absent

 - name: copy index.php to remote
   copy:
    src: ./template/index.php
    dest: /usr/local/httpd/htdocs/

 - name: remove /tmp/install_php.sh
   file:
    dest: /tmp/install_php.sh
    state: absent
    
 - name: remove /tmp/{{mtls_php | replace('.tar.gz','')}}
   file:
    dest: /tmp/{{mtls_php | replace('.tar.gz','')}}
    state: absent